version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - strapi-network

  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: mysql2
      DATABASE_HOST: mysql-container
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: 12345678
      DATABASE_SSL: "false"
    ports:
      - "80:8000"
    depends_on:
      - mysql

volumes:
  mysql-data:
  
networks:
  strapi-network:
