version: '3'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: D4r!4n4*
      MYSQL_DATABASE: strapi
      MYSQL_USER: root
      MYSQL_PASSWORD: D4r!4n4*
    ports:
      - "3306:3306"

  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: D4r!4n4*
      DATABASE_SSL: "false"
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  mysql-data: