services:
  mysql:
    image: mysql:lts
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: D4r!4n4*
      MYSQL_DATABASE: strapi
    ports:
      - "3306:3306"
    networks:
      - app-network

  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: mysql2
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: D4r!4n4*
      DATABASE_SSL: "false"
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
