version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: D4r!4n4*
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: D4r!4n4*
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

  strapi:
    build:
      context: .
      dockerfile: Dockerfile
      image: darigo/api-strapi:latest
    environment:
      DATABASE_CLIENT: mysql2
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: D4r!4n4*
      DATABASE_SSL: "false"
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  mysql-data:
