name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm install

      - name: Build Strapi app for demo
        run: npm run build:demo 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug
        run: echo "Debug information.."
          
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker-compose build strapi

      - name: Tag Docker image
        run: docker tag darigo/api-strapi:latest darigo/api-strapi:latest

      - name: Push Docker image to Docker Hub
        run: docker push darigo/api-strapi:latest

      - name: Run Docker Compose
        run: docker-compose up --build -d

      - name: Debug
        run: echo "Debug information..."
